= luke-service

This service showcases the combination of OpenTelemetry and Jakarta EE for observability purposes, based on Quarkus.

== Getting started

To get O11y with OpenTelemetry up and running, we are using the corresponding link:https://quarkus.io/guides/opentelemetry[Quarkus plugin]:

[source,xml]
----
<!-- pom.xml -->
include::pom.xml[tag=plugin,indent=0]
----

Now you already have tracing based on OpenTelemetry up and running with your Quarkus App (metrics and logging are currently not actived by default because they are relativly new in Quarkus available).

Todo some additional configuration, you have all the possibilities of link:https://quarkus.io/guides/config[Quarkus and MicroProfile Config] (the names of the config properities are the same as defined in the link:https://opentelemetry.io/docs/languages/java/configuration/[OpenTelemetry SDK], prefixed with quarkus):

[source,properties]
----
# application.properties
include::src/main/resources/application.properties[tag=config,indent=0]
----

If you are using unstructered logging, you can simply extend your log format with tracing informations (the plugin will automatically set the values in the MDC of your Logging-Framework, e.g. JBoss LogManager):

[source,properties]
----
# application.properties
include::src/main/resources/application.properties[tag=trace-log,indent=0]
----

== Span Link

Let's imagine that there is an operation that is not directly related to a workflow, but was triggered by another workflow as a result of an event, for example. This example is particularly common in event-driven systems.

This is where span links can be a great help, as they allow traces to be linked to each other without them having direct dependencies on each other.

The following code reacts on an async cdi event and creates an new trace for the async operation an links the new trace with the event emitting trace:

[source,java]
----
// EscapeBespin.java
include::src/main/java/org/kore/jakartaee/otel/EscapeBespin.java[tag=spanlink,indent=0]
----

== Baggage

To read out content of a received baggage, you can simply inject it an read out data:

[source,java]
----
// EscapeBespin.java
include::src/main/java/org/kore/jakartaee/otel/LooseHandResource.java[tag=baggage,indent=0]
----

== Custom Metrics

Thanks to the standardized API it is of course also possible, that you can create custom metrics out of application data:

[source,java]
----
// OpponentAngerLevelMetering.java
include::src/main/java/org/kore/jakartaee/otel/OpponentAngerLevelMetering.java[tag=metering,indent=0]
----