debugger.breakpoints.PHP-DBGP:# array
debugger.breakpoints.PHP-DBGP.array_type:org.netbeans.api.debugger.Breakpoint
debugger.breakpoints.PHP-DBGP.length:0
debugger.breakpoints.javascript-debugger:# array
debugger.breakpoints.javascript-debugger.array_type:org.netbeans.api.debugger.Breakpoint
debugger.breakpoints.javascript-debugger.length:0
debugger.breakpoints.jpda:# array
debugger.breakpoints.jpda.0:# org.netbeans.api.debugger.jpda.LineBreakpoint$LineBreakpointImpl
debugger.breakpoints.jpda.0.breakpointsToDisableCustomGroup:# null
debugger.breakpoints.jpda.0.breakpointsToDisableFileGroup:# null
debugger.breakpoints.jpda.0.breakpointsToDisableProjectGroup:# null
debugger.breakpoints.jpda.0.breakpointsToDisableTypeGroup:# null
debugger.breakpoints.jpda.0.breakpointsToEnableCustomGroup:# null
debugger.breakpoints.jpda.0.breakpointsToEnableFileGroup:# null
debugger.breakpoints.jpda.0.breakpointsToEnableProjectGroup:# null
debugger.breakpoints.jpda.0.breakpointsToEnableTypeGroup:# null
debugger.breakpoints.jpda.0.className:"org.kore.jakartaee.otel.EscapeBespin"
debugger.breakpoints.jpda.0.classNamePreferred:# null
debugger.breakpoints.jpda.0.condition:""
debugger.breakpoints.jpda.0.enabled:true
debugger.breakpoints.jpda.0.groupName:""
debugger.breakpoints.jpda.0.hitCountFilter:0
debugger.breakpoints.jpda.0.hitCountFilter_style:0
debugger.breakpoints.jpda.0.lineNumber:31
debugger.breakpoints.jpda.0.printText:"Breakpoint hit at line {lineNumber} in class {className} by thread {threadName}."
debugger.breakpoints.jpda.0.sourceRoot:# null
debugger.breakpoints.jpda.0.suspend:1
debugger.breakpoints.jpda.0.url:"file:/Users/koni/Development/Repositories/github/jakartaee-otel/luke-service/src/main/java/org/kore/jakartaee/otel/EscapeBespin.java"
debugger.breakpoints.jpda.1:# org.netbeans.api.debugger.jpda.LineBreakpoint$LineBreakpointImpl
debugger.breakpoints.jpda.1.breakpointsToDisableCustomGroup:# null
debugger.breakpoints.jpda.1.breakpointsToDisableFileGroup:# null
debugger.breakpoints.jpda.1.breakpointsToDisableProjectGroup:# null
debugger.breakpoints.jpda.1.breakpointsToDisableTypeGroup:# null
debugger.breakpoints.jpda.1.breakpointsToEnableCustomGroup:# null
debugger.breakpoints.jpda.1.breakpointsToEnableFileGroup:# null
debugger.breakpoints.jpda.1.breakpointsToEnableProjectGroup:# null
debugger.breakpoints.jpda.1.breakpointsToEnableTypeGroup:# null
debugger.breakpoints.jpda.1.className:"org.kore.jakartaee.otel.LooseHandResource"
debugger.breakpoints.jpda.1.classNamePreferred:# null
debugger.breakpoints.jpda.1.condition:""
debugger.breakpoints.jpda.1.enabled:true
debugger.breakpoints.jpda.1.groupName:""
debugger.breakpoints.jpda.1.hitCountFilter:0
debugger.breakpoints.jpda.1.hitCountFilter_style:0
debugger.breakpoints.jpda.1.lineNumber:42
debugger.breakpoints.jpda.1.printText:"Breakpoint hit at line {lineNumber} in class {className} by thread {threadName}."
debugger.breakpoints.jpda.1.sourceRoot:# null
debugger.breakpoints.jpda.1.suspend:1
debugger.breakpoints.jpda.1.url:"file:/Users/koni/Development/Repositories/github/jakartaee-otel/luke-service/src/main/java/org/kore/jakartaee/otel/LooseHandResource.java"
debugger.breakpoints.jpda.2:# org.netbeans.api.debugger.jpda.LineBreakpoint$LineBreakpointImpl
debugger.breakpoints.jpda.2.breakpointsToDisableCustomGroup:# null
debugger.breakpoints.jpda.2.breakpointsToDisableFileGroup:# null
debugger.breakpoints.jpda.2.breakpointsToDisableProjectGroup:# null
debugger.breakpoints.jpda.2.breakpointsToDisableTypeGroup:# null
debugger.breakpoints.jpda.2.breakpointsToEnableCustomGroup:# null
debugger.breakpoints.jpda.2.breakpointsToEnableFileGroup:# null
debugger.breakpoints.jpda.2.breakpointsToEnableProjectGroup:# null
debugger.breakpoints.jpda.2.breakpointsToEnableTypeGroup:# null
debugger.breakpoints.jpda.2.className:"org.kore.jakartaee.otel.LooseHandResource"
debugger.breakpoints.jpda.2.classNamePreferred:# null
debugger.breakpoints.jpda.2.condition:""
debugger.breakpoints.jpda.2.enabled:true
debugger.breakpoints.jpda.2.groupName:""
debugger.breakpoints.jpda.2.hitCountFilter:0
debugger.breakpoints.jpda.2.hitCountFilter_style:0
debugger.breakpoints.jpda.2.lineNumber:42
debugger.breakpoints.jpda.2.printText:"Breakpoint hit at line {lineNumber} in class {className} by thread {threadName}."
debugger.breakpoints.jpda.2.sourceRoot:# null
debugger.breakpoints.jpda.2.suspend:1
debugger.breakpoints.jpda.2.url:"file:/Users/koni/Development/Repositories/github/jakartaee-otel/luke-service/src/main/java/org/kore/jakartaee/otel/LooseHandResource.java"
debugger.breakpoints.jpda.array_type:org.netbeans.api.debugger.Breakpoint
debugger.breakpoints.jpda.length:0
debugger.connection_settings:# java.util.HashMap
debugger.connection_settings.0-key:"com.sun.jdi.SocketAttach"
debugger.connection_settings.0-value:# java.util.HashMap
debugger.connection_settings.0-value.0-key:"port"
debugger.connection_settings.0-value.0-value:"5005"
debugger.connection_settings.0-value.length:1
debugger.connection_settings.length:1
debugger.last_attach_type:"Java Debugger (JPDA)"
debugger.last_attaches.slot_0.attach_type:"Java Debugger (JPDA)"
debugger.last_attaches.slot_0.display_name:"Attach to localhost:5005"
debugger.last_attaches.slot_0.values.attaching_connector:"com.sun.jdi.SocketAttach"
debugger.last_attaches.slot_0.values.connection_settings:# java.util.HashMap
debugger.last_attaches.slot_0.values.connection_settings.0-key:"com.sun.jdi.SocketAttach"
debugger.last_attaches.slot_0.values.connection_settings.0-value:# java.util.HashMap
debugger.last_attaches.slot_0.values.connection_settings.0-value.0-key:"port"
debugger.last_attaches.slot_0.values.connection_settings.0-value.0-value:"5005"
debugger.last_attaches.slot_0.values.connection_settings.0-value.length:1
debugger.last_attaches.slot_0.values.connection_settings.length:1
debugger.last_attaches.used_slots:# array
debugger.last_attaches.used_slots.0:# java.lang.Integer
debugger.last_attaches.used_slots.0.primitiveWrapper:0
debugger.last_attaches.used_slots.array_type:java.lang.Integer
debugger.last_attaches.used_slots.length:1
debugger.last_attaching_connector:"com.sun.jdi.SocketAttach"
debugger.views.BreakpointsView.DefaultBreakpointColumn.columnWidth:329
debugger.views.BreakpointsView.DefaultBreakpointColumn.currentOrderNumber:0
debugger.views.BreakpointsView.DefaultBreakpointColumn.sorted:false
debugger.views.BreakpointsView.DefaultBreakpointColumn.sortedDescending:false
debugger.views.BreakpointsView.DefaultBreakpointColumn.visible:true
debugger.views.DefaultLocalsColumn.columnWidth:497
debugger.views.DefaultLocalsColumn.currentOrderNumber:0
debugger.views.DefaultLocalsColumn.sorted:false
debugger.views.DefaultLocalsColumn.sortedDescending:false
debugger.views.DefaultLocalsColumn.visible:true
debugger.views.HitCountBreakCount.currentOrderNumber:1
debugger.views.LocalsView.LocalsToString.currentOrderNumber:3
debugger.views.LocalsView.LocalsType.columnWidth:497
debugger.views.LocalsView.LocalsType.currentOrderNumber:1
debugger.views.LocalsView.LocalsType.sorted:false
debugger.views.LocalsView.LocalsType.sortedDescending:false
debugger.views.LocalsView.LocalsValue.columnWidth:497
debugger.views.LocalsView.LocalsValue.currentOrderNumber:2
debugger.views.LocalsView.LocalsValue.sorted:false
debugger.views.LocalsView.LocalsValue.sortedDescending:false
debugger.views.outlineOrdering:true
netbeans-JPDASession.EngineComponentsProvider.closedTopComponents.breakpointsView:false
netbeans-JPDASession.EngineComponentsProvider.closedTopComponents.callstackView:true
netbeans-JPDASession.EngineComponentsProvider.closedTopComponents.classes:true
netbeans-JPDASession.EngineComponentsProvider.closedTopComponents.debuggingView:false
netbeans-JPDASession.EngineComponentsProvider.closedTopComponents.evaluatorPane:false
netbeans-JPDASession.EngineComponentsProvider.closedTopComponents.localsView:false
netbeans-JPDASession.EngineComponentsProvider.closedTopComponents.resultsView:true
netbeans-JPDASession.EngineComponentsProvider.closedTopComponents.sessionsView:true
netbeans-JPDASession.EngineComponentsProvider.closedTopComponents.sources:true
netbeans-JPDASession.EngineComponentsProvider.closedTopComponents.threadsView:true
netbeans-JPDASession.EngineComponentsProvider.closedTopComponents.watchesView:true
netbeans-JPDASession.EngineComponentsProvider.minimizedTopComponents.breakpointsView:false
netbeans-JPDASession.EngineComponentsProvider.minimizedTopComponents.callstackView:false
netbeans-JPDASession.EngineComponentsProvider.minimizedTopComponents.classes:false
netbeans-JPDASession.EngineComponentsProvider.minimizedTopComponents.debuggingView:false
netbeans-JPDASession.EngineComponentsProvider.minimizedTopComponents.evaluatorPane:false
netbeans-JPDASession.EngineComponentsProvider.minimizedTopComponents.localsView:false
netbeans-JPDASession.EngineComponentsProvider.minimizedTopComponents.resultsView:false
netbeans-JPDASession.EngineComponentsProvider.minimizedTopComponents.sessionsView:false
netbeans-JPDASession.EngineComponentsProvider.minimizedTopComponents.sources:false
netbeans-JPDASession.EngineComponentsProvider.minimizedTopComponents.threadsView:false
netbeans-JPDASession.EngineComponentsProvider.minimizedTopComponents.watchesView:false
