= vader-service

This service showcases the combination of OpenTelemetry and Jakarta EE for observability purposes, based on OpenLiberty.

IMPORTANT: The following guide requires at least MicroProfile 7.1. You can find the details why this is important (especially for OpenLibety) in this link:https://openliberty.io/blog/2025/08/12/25.0.0.8.html[Blog Post].

== Getting started

To get O11y with OpenTelemetry up and running, we are using link:https://github.com/microprofile/microprofile-telemetry[MicroProfile Telemtry]. You can add just the MP Telemetry Spec, or simply include the whole MicroProfile Spec into your project:

[source,xml]
----
<!-- pom.xml -->
include::pom.xml[tag=mp,indent=0]
----

In case of OpenLiberty you also have to active the corresponding feature:

[source,xml]
----
<!-- server.xml -->
include::src/main/liberty/config/server.xml[tag=mp-feature,indent=0]
----

Now you already have tracing, metrics and even logging based on OpenTelemetry up and running with your OpenLiberty App.

Todo some additional configuration, you have all the possibilities of link:https://github.com/microprofile/microprofile-config[MP Config] (the names of the config properities are the same as defined in the link:https://opentelemetry.io/docs/languages/java/configuration/[OpenTelemetry SDK]):

[source,properties]
----
# microprofile-config.properties
include::src/main/resources/META-INF/microprofile-config.properties[tag=config,indent=0]
----

== Tracing

Let's have a look, on how to extend your traces with some additional informations. You can create Spans in a declarative style and also add additional attributes to your Spans via OTEL API:

[source,java]
----
include::src/main/java/org/kore/jakartaee/otel/CutHandResource.java[tag=fun-with-traces,indent=0]
----

== Baggage

Last but not least, you can also propagate application-defined properties associated with a distributed request or workflow execution thanks to Baggage.

In the following example, please note also the set of an Event into the current Span. This is really helpful, if there is something really important and you don't want to be required to look in log files.

[source,java]
----
include::src/main/java/org/kore/jakartaee/otel/CutHandResource.java[tag=fun-with-baggage,indent=0]
----

== Instrumentation without MicroProfile Telemetry

If you want to instrument your application without MicroProfile Telemetry (e.g. you are using Spring), the following code showcases you how to instrument your app directly with the opentelemetry-javaagent.

[source,xml]
----
<!-- pom.xml -->
include::pom.xml[tag=agent,indent=0]
----
